#!/usr/bin/env python3

import gzip
import io
import collections

def gzopen_r(path, mode = 'r'):
	file = open(path, 'rb')

	if file.peek(2)[:2] == b'\x1f\x8b':
		file = gzip.GzipFile( fileobj = file, mode = 'rb' )
	if 'b' not in mode:
		file = io.TextIOWrapper(file)

	return file

def chomp(line):
	if line.endswith('\n'):
		line = line[:-1]
	if line.endswith('\r'):
		line = line[:-1]

	return line

def chomp_from(stream):
	for line in stream:
		yield chomp(line)

if __name__ == '__main__':
	import sys

	args = sys.argv[1:]

	if len(args) < 1:
		sys.stderr.write(f'Usage: { sys.argv[0] } input.vcf [...]' + '\n')
		sys.exit(1)

	seen = collections.OrderedDict()

	for arg in args:
		with gzopen_r(arg, 'r') as stream:
			for line in chomp_from(stream):
				if line.startswith('##'):
					if line not in seen:
						seen[line] = True
						sys.stdout.write( line + '\n' )
				elif line.startswith('#'):
					pass
				else:
					break
